---
# tasks file for generate-ssl-cert
- name: Add v3 CA block to OpenSSL config (bugfix).
  become: yes
  lineinfile:
    dest: /etc/ssl/openssl.cnf
    regexp: '^\[v3_ca\]'
    line: '[v3_ca]'
    state: present
    backup: yes

- name: Add IPv4 address to OpenSSL config.
  become: yes
  lineinfile:
    dest: /etc/ssl/openssl.cnf
    insertafter: '\[v3_ca\]'
    regexp: '^subjectAltName'
    line: 'subjectAltName = IP:{{ ssl_certificate_ip_address | mandatory }}'
    backup: yes
    state: present

- name: Create system group for managing permissions.
  become: yes
  group:
    name: "{{ item }}"
    system: yes
  with_items: "{{ ssl_certificate_create_users }}"

- name: Create system account for managing permissions.
  become: yes
  user:
    name: "{{ item }}"
    group: "{{ item }}"
    system: yes
  with_items: "{{ ssl_certificate_create_users }}"

- name: Create certificate directories.
  become: yes
  file:
    state: directory
    path: "{{ item.path|dirname }}"
  with_items: "{{ [ssl_certificate_permissions_map.cert, ssl_certificate_permissions_map.key] }}"

- name: Check for existing OpenSSL certificate file.
  stat:
    path: "{{ ssl_certificate_permissions_map.cert.path }}"
  register: existing_openssl_cert_result

- name: Generate OpenSSL certificate file.
  become: yes
  command: >
    openssl req -config /etc/ssl/openssl.cnf -x509
    -days 3650 -batch -nodes -newkey rsa:{{ ssl_certificate_bit_length }}
    -keyout {{ ssl_certificate_permissions_map.key.path }}
    -out {{ ssl_certificate_permissions_map.cert.path }}
  when: existing_openssl_cert_result.stat.exists == false
        or ssl_certificate_force_generate == true

- name: Set permissions on OpenSSL files.
  become: yes
  file:
    state: file
    path: "{{ item.path }}"
    mode: "{{ item.mode }}"
    owner: "{{ item.owner }}"
    owner: "{{ item.group }}"
  with_items: "{{ [ssl_certificate_permissions_map.cert, ssl_certificate_permissions_map.key] }}"

- name: Fetch OpenSSL certificate file back to localhost.
  fetch:
    src: "{{ ssl_certificate_permissions_map.cert.path }}"
    dest: files/
    flat: true
    fail_on_missing: true
