---
# tasks file for generate-ssl-cert
- name: add IPv4 address to openssl config
  blockinfile:
    dest: /etc/ssl/openssl.cnf
    backup: yes
    content: |
      [v3_ca]
      subjectAltName = IP:{{ ssl_certificate_ip_address | mandatory}}

- name: generate cert file
  command: >
    openssl req -config /etc/ssl/openssl.cnf -x509
    -days 3650 -batch -nodes -newkey rsa:2048
    -keyout {{ ssl_certificate_directory }}/private/{{ ssl_certificate_basename }}.key
    -out {{ ssl_certificate_directory }}/certs/{{ ssl_certificate_basename }}.crt
  args:
    creates: "{{ ssl_certificate_directory }}/certs/{{ ssl_certificate_basename }}.crt"


- name: fetch back cert file
  fetch:
    src: "{{ ssl_certificate_directory }}/certs/{{ ssl_certificate_basename }}.crt"
    dest: files/
    flat: true
    fail_on_missing: true
