---
# tasks file for generate-ssl-cert
- name: Add v3 CA block to OpenSSL config (bugfix).
  sudo: yes
  lineinfile:
    dest: /etc/ssl/openssl.cnf
    regexp: '^\[v3_ca\]'
    line: '[v3_ca]'
    state: present
    backup: yes

- name: Add IPv4 address to OpenSSL config.
  sudo: yes
  lineinfile:
    dest: /etc/ssl/openssl.cnf
    insertafter: '\[v3_ca\]'
    regexp: '^subjectAltName'
    line: 'subjectAltName = IP:{{ ssl_certificate_ip_address | mandatory }}'
    backup: yes
    state: present

- name: Create certificate directories.
  sudo: yes
  file:
    state: directory
    path: "{{ ssl_certificate_directory }}/{{ item }}"
    mode: "0755"
    owner: root
    group: root
  with_items:
    - certs
    - private

- name: Generate OpenSSL certificate file.
  sudo: yes
  command: >
    openssl req -config /etc/ssl/openssl.cnf -x509
    -days 3650 -batch -nodes -newkey rsa:{{ ssl_certificate_bit_length }}
    -keyout {{ ssl_certificate_directory }}/private/{{ ssl_certificate_basename }}.key
    -out {{ ssl_certificate_directory }}/certs/{{ ssl_certificate_basename }}.crt
  args:
    creates: "{{ ssl_certificate_directory }}/certs/{{ ssl_certificate_basename }}.crt"

- name: Fetch OpenSSL certificate file back to localhost.
  fetch:
    src: "{{ ssl_certificate_directory }}/certs/{{ ssl_certificate_basename }}.crt"
    dest: files/
    flat: true
    fail_on_missing: true
